### ISSUE TITLE
1.12.2启动提示需要1.13及更高版本

### ISSUE THREAD

**Issue by 1zyao** [CSneko/ctLib#3]
加载器：cleanroom
java版本：21
插件版本：ctLib0.0.15
日志：
[06:40:47] [Client thread/WARN] [FML]: ****************************************
[06:40:47] [Client thread/WARN] [FML]: * The mod ctlib has been identified as a probable 1.13 or greater mod. Things will not work well.
[06:40:47] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:144)
[06:40:47] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:128)
[06:40:47] [Client thread/WARN] [FML]: *  at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source)
[06:40:47] [Client thread/WARN] [FML]: *  at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
[06:40:47] [Client thread/WARN] [FML]: *  at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[06:40:47] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.ModContainerFactory.build(ModContainerFactory.java:73)...
[06:40:47] [Client thread/WARN] [FML]: ****************************************
[06:40:47] [Client thread/INFO] [FML]: Mod ctlib is missing the required element 'name'. Substituting ctlib
[06:40:47] [Client thread/WARN] [FML]: Mod ctlib is missing the required element 'version' and no fallback can be found. Substituting '1.0'.
[06:40:47] [Thread-2/INFO] [FML]: Using alternative sync timing : 200 frames of Display.update took 3185584300 nanos
[06:40:47] [Client thread/INFO] [FML]: Forge Mod Loader has identified 85 mods to load
[06:40:47] [Client thread/FATAL] [FML]: The mod ctlib does not wish to run in Minecraft version Minecraft 1.12.2. You will have to remove it to play.
[06:40:47] [Client thread/FATAL] [FML]: Wrong Minecraft version for ctlib
[06:40:47] [Client thread/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.WrongMinecraftVersionException: Wrong Minecraft version for ctlib
Wrong Minecraft Versions!
Mod: ctlib
Location: G:\尧游戏等文件\RETE-TEST\.minecraft\mods\ctLibMod-0.0.15.jar
Expected: [1.13,)
Current: Minecraft 1.12.2

	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:252) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandlerMixin.java:231) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(MinecraftMixin.java:467) [bib.class:?]
	at net.minecraft.client.Minecraft.run(MinecraftMixin.java:5079) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.cleanroommc.bouncepad.Bouncepad.launch(Bouncepad.java:169) [bouncepad-0.4.28-cursed.jar:?]
	at com.cleanroommc.bouncepad.Bouncepad.main(Bouncepad.java:42) [bouncepad-0.4.28-cursed.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) [JavaWrapper.jar:?]
[06:40:47] [Client thread/WARN] [FML]: EventBus 0 shutting down - future events will not be posted.
截图：
![image](https://github.com/CSneko/ctLib/assets/107829654/395be1d9-fd75-46ef-b07e-58f4c82b834b)

**Comment by CSneko** [comment]
尽管该模组并没有对Minecraft游戏版本有任何要求，但由于使用了Java11以上才有的包，因此要求运行在Java11以上，也许加载器发现该模组使用java11编译(通常情况下，1.12及一下的模组只会使用java8编译)，认定为要求至少1.13才能运行，除非能够将模组代码中所有的java8以上的类全部替换为java8有的并使用java8重新编译，否则很难解决这个问题

**Comment by 1zyao** [comment]
没有有关渲染的应该还算好移植
