### ISSUE TITLE
The plug-in fails to load in the leaves server version 1.20.1

### ISSUE THREAD

**Issue by BZxmxs** [CSneko/ctLib#6]
[00:13:50] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'ctLibPlugin-0.1.11.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.12
	at org.bukkit.craftbukkit.v1_20_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:379) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:119) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:517) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1095) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
[00:13:50] [Server thread/WARN]: [org.bukkit.craftbukkit.v1_20_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[00:13:52] [Server thread/WARN]: Legacy plugin McPing v1.0-SNAPSHOT does not specify an api-version.
[00:13:52] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'toNeko-1.1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `com.crystalneko.toneko.ToNeko'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:517) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1095) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.crystalneko.toneko.ToNeko
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:529) ~[?:?]
	at java.lang.Class.forName(Class.java:508) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[leaves-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 10 more

**Comment by BZxmxs** [comment]
I accidentally sent another plug-in incorrectly

**Comment by CSneko** [comment]
Seems that you use toNeko-1.1.0,But this version now is not supported bukkit,try to use this version : https://modrinth.com/plugin/toneko

**Comment by BZxmxs** [comment]
使用了插件版本后仍然出现报错，
[19:38:23 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'ctLibPlugin-0.1.11.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.12
        at org.bukkit.craftbukkit.v1_20_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:379) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:119) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:517) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1095) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309) ~[leaves-1.20.1.jar:git-Leaves-"847357b"]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
[19:38:23 警告]: [org.bukkit.craftbukkit.v1_20_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[19:38:27 警告]: Legacy plugin McPing v1.0-SNAPSHOT does not specify an api-version.

**Comment by BZxmxs** [comment]
像是某种API版本导致
